name: Manipulate JSON files
description: Reads or writes a value of a property specified as dot-separated path from defined JSON file
author: "https://github.com/amochkin"
inputs:
  file:
    description: "Path to JSON file; default is `package.json`"
    default: "package.json"
  mode:
    description: "Mode of operation (`read`/`write`); default is `read`"
    default: "read"
  property:
    description: "Dot-separated path to property (for example `a.b`)`"
    required: true
  value:
    description: "Value to write to property, required for `write` mode"
  value_type:
    description: "Type of value to write to property (`string`/`number`/`boolean`/`object`); default is `string`"
    default: "string"
  quiet:
    description: "Do not output value to the log; default is `false`"
    default: "false"
  fallback:
    description: "Fallback file to use if file is not found"
  override_with:
    description: "Override read value with this value"
  use_override:
    description: "Flag: Use override value instead of read value"
    default: "false"
  output_name:
    description: "Name of output variable to use"
    default: "value"
  output_file:
    description: "Path to file to write output value to. Defaults to the same file as input (write in-place)"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: settings
  color: blue
outputs:
  value:
    description: "Value of property (only if mode is `read`). Can be override with `output_name` input."
