name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build

      - name: Create release
        uses: softprops/action-gh-release@v1
